# Generated by Django 4.1.1 on 2022-09-16 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('dob', models.DateField(max_length=8)),
                ('education', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='img/%y')),
                ('user', models.CharField(default='myname', max_length=30, null=True)),
            ],
        ),
    ]
