# Generated by Django 4.1.1 on 2022-09-16 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadtemplate',
            name='template',
            field=models.CharField(choices=[('t1', 't1️'), ('t2', 't2️'), ('t3', 't3️')], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
