# Generated by Django 4.1.1 on 2022-09-16 08:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_uploadtemplate_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadtemplate',
            name='uniqueID',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
